# PyLGMath Tutorial

Welcome to the PyLGMath tutorial! PyLGMath is a Lie Group Math library implemented in Python for handling geometry in state estimation problems in robotics. It is used to store, manipulate, and apply three-dimensional rotations and transformations and their associated uncertainties. There are no minimal, constraint-free, singularity-free representations for these quantities, so lgmath exploits two different representations for the nominal and noisy parts of the uncertain random variable.
- Nominal rotations and transformations are represented using their composable, singularity-free matrix Lie groups, $SO(3)$ and $SE(3)$.
- Their uncertainties are represented as multiplicative perturbations on the minimal, constraint-free vectorspaces of their Lie algebras, $so(3)$ and $se(3)$.

This library uses concepts and mathematics described in Timothy D. Barfoot's book State Estimation for Robotics. This tutorial walks you through all the functions offered in this library with link to the book.

In [27]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "last_expr_or_assign"
import numpy as np
import numpy.linalg as npla

## $SO(3)$ Operators


In [28]:
from pylgmath import so3op

### **hat** ($\land$) and **hatinv** ($\lor$)

Converts a 3 by 1 vector to/from a 3 by 3 skew symmetric matrix.

$$\mathbf{u}^\land = \begin{bmatrix} u_1 \\ u_2 \\ u_3 \end{bmatrix}^\land := \begin{bmatrix} 0 & -u_3 & u_2 \\ u_3 & 0 & -u_1 \\ -u_2 & u_1 & 0 \end{bmatrix}$$


In [22]:
u = np.random.uniform(size=(3, 1))  # requires shape of u to be [..., 3, 1]

array([[0.34298154],
       [0.00924816],
       [0.44163282]])

In [25]:
u_hat = so3op.hat(u)

array([[ 0.        , -0.44163282,  0.00924816],
       [ 0.44163282,  0.        , -0.34298154],
       [-0.00924816,  0.34298154,  0.        ]])

In [26]:
u_hatinv = so3op.hatinv(u_hat)

array([[0.34298154],
       [0.00924816],
       [0.44163282]])

### **vec2rot** and **rot2vec**

Transforms a rotation between its matrix Lie group representation ($\mathbf{C}$) and its Lie algebra vector representation ($\bm{\phi}$) using the exponential map

$$\mathbf{C} = \exp(\bm{\phi}^\land) = \sum_{n=1}^\infty \frac{1}{n!} (\bm{\phi}^\land)^n \quad \text{and} \quad \bm{\phi} = {\ln(\mathbf{C})}^\lor = \sum_{n=1}^\infty \frac{(-1)^{n-1}}{n} (\mathbf{C} - \mathbf{1})^n$$

When going from Lie algebra to Lie group, we can use the analytical solution

$$\exp(\bm{\phi}^\land) = \cos\phi \mathbf{1} + (1-\cos \phi) \mathbf{a} \mathbf{a}^T + \sin \phi \mathbf{a}^T$$

Note that this mapping is *surjective-only*, and we assume the angle of rotation $|\bm{\phi}| < \pi$.

When going from Lie group to Lie algebra,